@startuml
actor client
client -> CustomerMessageController: send message request
activate CustomerMessageController #FFBBBB

CustomerMessageController -> wechat: get access token
activate wechat #FFBBBB
CustomerMessageController <-- wechat: response access token

CustomerMessageController -> wechat: call tencent send message interface
CustomerMessageController <-- wechat: send message response
deactivate wechat

CustomerMessageController -> oracle: save message to T_MESSAGE table

client <-- CustomerMessageController: send message response
deactivate CustomerMessageController
@enduml