@startuml
Jack -> Bob: Authentication Request
activate Bob #FFBBBB
Bob --> Jack: Authentication Response
note right: this is a note
Bob -> Tom: Another authentication Request
Bob <-- Tom: another authentication Response
deactivate Bob

actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
activate Foo2 #FFBBBB
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections

participant User

User -> A: DoWork
activate A #FFBBBB

A -> B: Internal call
activate A #DarkSalmon

A -> B: << createRequest >>
activate B

B --> A: RequestCreated
deactivate B
deactivate A
A -> User: Done
deactivate A
@enduml
